[Interface]
PrivateKey = IGmpxSFyop5zUsYfUcoUFCBQIrNeksyLinfe/pVnyEg=
Address    = 10.8.0.2/24
DNS        = 1.1.1.1

[Peer]
PublicKey           = KcBvUf11r630CFJ5G1RILeuooYJPYxJcuDu7Vu1XLxk=
Endpoint            = 20.8.2.11:51820
AllowedIPs          = 10.8.0.0/24, 172.20.0.0/16
PersistentKeepalive = 25