[Interface]
Address = 10.8.0.1/24
ListenPort = 51820
PrivateKey = qHIwdhwTcPyYtjcWs4jhegm6g/V4rWh4eWIKc2e+6WY=

PostUp   = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

[Peer]
PublicKey  = VIs875Znrtkz2q4LD+bqvCKUCatythWhOe97RyMJEhU=
AllowedIPs = 10.8.0.2/32